name: Dependent Jobs Workflow

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Build Project
        run: echo "Building the project..."
  test:
    runs-on: ubuntu-latest
    needs: build # Runs only after "build" job
    steps:
      - name: Run Tests
        run: echo "Running tests..."

  deploy:
    runs-on: ubuntu-latest
    needs: [build, test] # Runs only after both "build" and "test" jobs
    steps:
      - name: Deploy Application
        run: echo "Deploying the application..."